:team_number: 3
:all_members:
  - :name: 'やまぐち'
    :japanese: true
  - :name: 'はすみ'
    :japanese: true
  - :name: 'みとも'
    :japanese: true
  - :name: 'タイン'
    :japanese: false
  - :name: 'ポール'
    :japanese: false
  - :name: 'ハー'
    :japanese: false
  - :name: 'シヴァン'
    :japanese: false
  - :name: 'おしだ'
    :japanese: true
  - :name: 'おくだ'
    :japanese: true
